# Generated by Django 5.1.3 on 2024-12-03 17:36

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ukr', models.CharField(max_length=100, unique=True, verbose_name='Назва українською')),
                ('name_eng', models.CharField(max_length=100, unique=True, verbose_name='Назва англійською')),
                ('link', models.CharField(max_length=100, unique=True, verbose_name='Посилання на вправу')),
                ('desc', tinymce.models.HTMLField(verbose_name='Опис вправи')),
            ],
            options={
                'verbose_name': 'вправу',
                'verbose_name_plural': 'Вправи',
                'db_table': 'Exercises',
            },
        ),
    ]
