# Generated by Django 5.1.1 on 2024-10-04 21:45

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва')),
                ('link', models.CharField(max_length=100, unique=True, verbose_name='Посилання')),
                ('desc', tinymce.models.HTMLField(verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'вправу',
                'verbose_name_plural': 'Вправи',
            },
        ),
    ]
